call test.cmd %* testfiles\0
call test.cmd %* testfiles\1
call test.cmd %* testfiles\2
call test.cmd %* testfiles\3
call test.cmd %* testfiles\4
call test.cmd %* D:\testing\!
call test.cmd %* D:\testing\dll100.dll
call test.cmd %* D:\testing\dll700.dll
call test.cmd %* D:\testing\!!!\5g
call test.cmd %* D:\testing\!!!\vm
